### ISSUE TITLE
Implement Social Login in ASP.NET Core Web API for Task Management

### ISSUE THREAD

**Issue by fullstackdev0305** [KGG-Dev-Course/taskmaster-api#28]
### Description:
To augment our task management system, we're focusing on enabling social login functionality in the backend, which is developed using ASP.NET Core Web API. The aim is to facilitate user authentication via various social platforms using tokens obtained from the frontend.

### Objective:
Integrate social login endpoints and authentication mechanisms in the ASP.NET Core Web API to support login via popular social platforms.

### Tasks:

1. Configuration of Authentication Middleware:
- Implement authentication middleware for handling social login tokens.
- Configure the ASP.NET Core Web API to authenticate users using tokens from social platforms.

2. Endpoints for Social Login:
- Create endpoints to handle authentication requests from the frontend for each social platform (e.g., Google, Facebook, etc.).
- Implement logic to verify social login tokens and extract user data.

3. User Data Handling:
- Define mechanisms to manage user data obtained from social login.
- Ensure seamless integration with the existing user management system.

**Comment by chenxidev1129** [comment]
@kgg0305 Please confirm login design for social login(Google and Facebook)
@smartwebdev2023 Please set the environment in Facebook

**Comment by chenxidev1129** [comment]
I think we don't need to update the Backennd for Social login.
I made like this on Frontend:
- Sign:
`this.loginForm.patchValue({
  username: user.email.split('@')[0],
  password: "Password!" + user.id
});`
- Signup:
`this.registerForm.patchValue({
  email: user.email,
  username: user.email.split('@')[0],
  password: "Password!" + user.id
});`

So we don't need to update the backend for that.

**Comment by fullstackdev0305** [comment]
Absolutely! That's a smart approach to coding.

**Comment by johnsmith0305** [comment]
@chenxidev1129 Okay. Thank you.
We can close this issue without PR.
